<a href="https://colab.research.google.com/github/mahanthianuradha/Player-score-calculator/blob/master/AIML_Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 2, 5],
    'age':         [25, np.nan, 35, np.nan, np.nan, 40],
    'city':        ['Mumbai', 'Delhi', np.nan, 'Mumbai', 'Delhi', np.nan],
    'gender':      ['Male', 'Female', 'Female', 'Male', 'Female', 'Male'],
    'annual_income': [40000, 80000, 60000, 120000, 80000, 95000]
})
#print(df)
#Task 1 — Clean the Data
#Impute missing values in age with the median and in city with the mode
df['age'] = df['age'].fillna(df['age'].median())

df['city'] = df['city'].fillna(df['city'].mode()[0])
df
#Remove any duplicate rows
print(f"\n\n\n")
df = df.drop_duplicates()

df

   customer_id   age    city  gender  annual_income
0            1  25.0  Mumbai    Male          40000
1            2  35.0   Delhi  Female          80000
2            3  35.0   Delhi  Female          60000
3            4  35.0  Mumbai    Male         120000
5            5  40.0   Delhi    Male          95000

In [ ]:
from sklearn.preprocessing import OneHotEncoder , LabelEncoder

In [ ]:
df = pd.get_dummies(df, columns=['city'])

df

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0    Male          40000       False         True
1            2  35.0  Female          80000        True        False
2            3  35.0  Female          60000        True        False
3            4  35.0    Male         120000       False         True
5            5  40.0    Male          95000        True        False

In [ ]:
le = LabelEncoder()
df['gender'] = le.fit_transform(df['gender'])
df

   customer_id   age  gender  annual_income  city_Delhi  city_Mumbai
0            1  25.0       1          40000       False         True
1            2  35.0       0          80000        True        False
2            3  35.0       0          60000        True        False
3            4  35.0       1         120000       False         True
5            5  40.0       1          95000        True        False

In [2]:
#Task 3 — Scale Numerical Features
#Scale age and annual_income using both methods below on the cleaned dataframe, and print the results of each
#Min-Max Scaling (using MinMaxScaler)
from mlxtend.preprocessing import minmax_scaling
minmax_scaling(df, columns=['age', 'annual_income'])

ValueError: could not convert string to float: 'Male'

In [ ]:
#Standardisation (using StandardScaler)

from sklearn.preprocessing import StandardScaler
# standardization
object= StandardScaler()
#scale = object.fit_transform(i_data)
#print(scale)
scale = object.fit_transform(df,columns = ['age', 'annual_income'])
print(scale)

TypeError: StandardScaler.fit() got an unexpected keyword argument 'columns'