<a href="https://colab.research.google.com/github/mahanthianuradha/Player-score-calculator/blob/master/Leakage_%26_Imbalance_cars_messy_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1 — Explore and Identify Issues

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = "https://drive.google.com/uc?export=download&id=14Yxdyp_vTM94nBjNH2igpsfjvMgbefWO"

df = pd.read_csv(url)
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  object
 2   brand              15661 non-null  object
 3   model              15661 non-null  object
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  object
 6   seller_type        15661 non-null  object
 7   fuel_type          15661 non-null  object
 8   transmission_type  15661 non-null  object
 9   mileage            14376 non-null  object
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.7+ MB

(15661, 14)

In [ ]:
df.shape

(15661, 14)

In [ ]:
df.describe()

,Unnamed: 0,vehicle_age,engine,max_power,seats,selling_price
count,15661.000000,15661.000000,13792.000000,14862.000000,15218.000000,1.550300e+04
mean,9808.189643,6.036843,1480.489342,100.513582,5.324418,1.032764e+06
std,5642.981540,3.015072,511.446057,42.854632,0.805993,1.607380e+07
min,0.000000,0.000000,793.000000,38.400000,0.000000,5.000000e+02
25%,4901.000000,4.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9858.000000,6.000000,1248.000000,88.500000,5.000000,5.550000e+05
75%,14666.000000,8.000000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,6592.000000,626.000000,9.000000,1.000000e+09

In [ ]:
df.isnull().sum()

Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1285
engine               1869
max_power             799
seats                 443
selling_price         158
dtype: int64

Observations :
1.kilometers driven and mileage given as object.
2.min and max car price are also need to check because those are abnormal.
3.And also the min nummber of car seats is zero which is impossible.
4.column Unnamed  = 0 which is not useful.

Task 2 — Clean the Data
Fix the issues identified:
drop null target rows, impute missing input features, strip and lowercase the brand column, extract numeric values from the mileage column, and remove duplicates.

In [ ]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='object')

In [ ]:
df = df.drop(columns=['Unnamed: 0'])
df.head(10)

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
5,Hyundai i10,Hyundai,i10,12,73000,Dealer,Petrol,Manual,20.36,1197.0,78.90,5.0,190000.0
6,Hyundai i20,Hyundai,i20,12,88000,Dealer,Petrol,Manual,18.5,NaN,80.00,5.0,275000.0
7,Maruti Wagon R,Maruti,Wagon R,7,50000,Individual,Petrol,Manual,20.51,NaN,67.04,5.0,351000.0
8,Ford Freestyle,Ford,Freestyle,2,30000,individual,Diesel,Manual,24.4,1498.0,98.63,5.0,775000.0
9,Maruti Swift Dzire,Maruti,Swift Dzire,10,75220,Dealer,Diesel,Manual,19.3,1248.0,73.90,5.0,390000.0

In [ ]:
df = df.dropna(subset = ['selling_price'])
df

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [ ]:
df.isnull().sum()

car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1269
engine               1852
max_power             791
seats                 438
selling_price           0
dtype: int64

 Impute missing input features

In [ ]:
#extract numeric values from the mileage column
df['mileage'] = df['mileage'].astype(str).str.replace('kmpl', '').str.replace('kmp', '').str.strip()

df['mileage'] = pd.to_numeric(df['mileage'], errors='coerce')
df['mileage'].head()

0    19.87
1    33.54
2      NaN
3    15.40
4    16.00
Name: mileage, dtype: float64

In [ ]:
# impute missing input features:
for col in ['engine', 'mileage', 'max_power']:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)
    print(f"Filled {col} missing values with median: {median_val}")

Filled engine missing values with median: 1248.0
Filled mileage missing values with median: 19.67
Filled max_power missing values with median: 88.5

In [ ]:
seats_mode = df['seats'].mode()[0]
df['seats'] = df['seats'].fillna(seats_mode)
print(f"Filled seats missing values with mode: {seats_mode}")

Filled seats missing values with mode: 5.0

In [ ]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [ ]:
#remove duplicates:
cat_cols = ['car_name', 'brand', 'seller_type', 'fuel_type', 'transmission_type']

for col in cat_cols:
    unique_vals = df[col].unique()
    print(f"\n{col} {len(unique_vals)} unique values): ")
    print(sorted(unique_vals))

car_name 121 unique values):
['Audi A4', 'Audi A6', 'Audi A8', 'Audi Q7', 'BMW 3', 'BMW 5', 'BMW 6', 'BMW 7', 'BMW X1', 'BMW X3', 'BMW X4', 'BMW X5', 'BMW Z4', 'Bentley Continental', 'Datsun GO', 'Datsun RediGO', 'Datsun redi-GO', 'Ferrari GTC4Lusso', 'Force Gurkha', 'Ford Aspire', 'Ford Ecosport', 'Ford Endeavour', 'Ford Figo', 'Ford Freestyle', 'Honda Amaze', 'Honda CR', 'Honda CR-V', 'Honda City', 'Honda Civic', 'Honda Jazz', 'Honda WR-V', 'Hyundai Aura', 'Hyundai Creta', 'Hyundai Elantra', 'Hyundai Grand', 'Hyundai Santro', 'Hyundai Tucson', 'Hyundai Venue', 'Hyundai Verna', 'Hyundai i10', 'Hyundai i20', 'ISUZU MUX', 'Isuzu D-Max', 'Isuzu MUX', 'Jaguar F-PACE', 'Jaguar XE', 'Jaguar XF', 'Jeep Compass', 'Jeep Wrangler', 'Kia Carnival', 'Kia Seltos', 'Land Rover Rover', 'Lexus ES', 'Lexus NX', 'Lexus RX', 'MG Hector', 'Mahindra Alturas', 'Mahindra Bolero', 'Mahindra KUV', 'Mahindra KUV100', 'Mahindra Marazzo', 'Mahindra Scorpio', 'Mahindra Thar', 'Mahindra XUV300', 'Mahindra XUV500', 'Maruti Alto', 'Maruti Baleno', 'Maruti Celerio', 'Maruti Ciaz', 'Maruti Dzire LXI', 'Maruti Dzire VXI', 'Maruti Dzire ZXI', 'Maruti Eeco', 'Maruti Ertiga', 'Maruti Ignis', 'Maruti S-Presso', 'Maruti Swift', 'Maruti Swift Dzire', 'Maruti Vitara', 'Maruti Wagon R', 'Maruti XL6', 'Maserati Ghibli', 'Maserati Quattroporte', 'Mercedes-AMG C', 'Mercedes-Benz C-Class', 'Mercedes-Benz CLS', 'Mercedes-Benz E-Class', 'Mercedes-Benz GL-Class', 'Mercedes-Benz GLS', 'Mercedes-Benz S-Class', 'Mini Cooper', 'Nissan Kicks', 'Nissan X-Trail', 'Porsche Cayenne', 'Porsche Macan', 'Porsche Panamera', 'Renault Duster', 'Renault KWID', 'Renault Triber', 'Rolls-Royce Ghost', 'Skoda Octavia', 'Skoda Rapid', 'Skoda Superb', 'Tata Altroz', 'Tata Harrier', 'Tata Hexa', 'Tata Nexon', 'Tata Safari', 'Tata Tiago', 'Tata Tigor', 'Toyota Camry', 'Toyota Fortuner', 'Toyota Glanza', 'Toyota Innova', 'Toyota Yaris', 'Volkswagen Polo', 'Volkswagen Vento', 'Volvo S90', 'Volvo XC', 'Volvo XC60', 'Volvo XC90']

brand 80 unique values):
[' Audi', ' Audi ', ' BMW', ' BMW ', ' Datsun', ' Datsun ', ' Ferrari ', ' Ford', ' Ford ', ' Honda', ' Honda ', ' Hyundai', ' Hyundai ', ' ISUZU ', ' Land Rover', ' MG ', ' Mahindra', ' Mahindra ', ' Maruti', ' Maruti ', ' Mercedes-AMG ', ' Mercedes-Benz ', ' Mini ', ' Nissan ', ' Porsche', ' Renault', ' Renault ', ' Skoda', ' Skoda ', ' Tata', ' Tata ', ' Toyota', ' Toyota ', ' Volkswagen', ' Volkswagen ', 'Audi', 'Audi ', 'BMW', 'BMW ', 'Bentley', 'Datsun', 'Datsun ', 'Force', 'Ford', 'Ford ', 'Honda', 'Honda ', 'Hyundai', 'Hyundai ', 'ISUZU', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Land Rover', 'Lexus', 'MG', 'Mahindra', 'Mahindra ', 'Maruti', 'Maruti ', 'Maserati', 'Mercedes-Benz', 'Mercedes-Benz ', 'Mini', 'Nissan', 'Porsche', 'Renault', 'Renault ', 'Rolls-Royce', 'Skoda', 'Skoda ', 'Tata', 'Tata ', 'Toyota', 'Toyota ', 'Volkswagen', 'Volkswagen ', 'Volvo', 'Volvo ']

seller_type 9 unique values):
['DEALER', 'Dealer', 'Delaer', 'Individual', 'Individuall', 'Individul', 'Trustmark Dealer', 'dealer', 'individual']

fuel_type 14 unique values):
[' Diesel', ' Petrol', 'CNG', 'DIESEL', 'Diesel', 'Electric', 'LPG', 'PETROL', 'Petrol', 'Petrol ', 'diesel', 'diesel ', 'petrol', 'petrol ']

transmission_type 2 unique values):
['Automatic', 'Manual']

In [ ]:
df.duplicated().sum()

np.int64(261)

In [ ]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

,vehicle_age,mileage,engine,max_power,seats,selling_price
count,15242.000000,15242.000000,15242.000000,15242.000000,15242.000000,1.524200e+04
mean,6.037659,19.692756,1452.969623,99.982870,5.314526,1.037976e+06
std,3.016265,4.002252,486.344414,41.947384,0.796545,1.621050e+07
min,0.000000,4.000000,793.000000,38.400000,0.000000,5.000000e+02
25%,4.000000,17.092500,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,19.670000,1248.000000,88.500000,5.000000,5.550000e+05
75%,8.000000,22.320000,1498.000000,113.415000,5.000000,8.250000e+05
max,29.000000,33.540000,6592.000000,626.000000,9.000000,1.000000e+09